radon-project/radon

core/datatypes.py

Fixed array multiply issue.

---

README.md

docs: Updated readme with new labels.

---

.gitignore
core/builtin_funcs.py
core/datatypes.py
core/errors.py
examples/python_api.rn

**fixing:** `core/errors.py`
refactor: added docs string to all methods and functions.
fix: indent issues with `string_with_arrows()` function.
working on #10 #11

PyAPI implementation issue #10 #11

---

core/builtin_funcs.py
core/datatypes.py

The issue was with instance checking and evaluation. It is now fixed with this pull request. 
#28 closed by this.

Issue arr find method #28

---

core/datatypes.py
examples/arrays.rn

Issue Number multiply by Number in datatypes #30

---

bug.rn
core/interpreter.py
examples/scoping.rn
stdlib/System.rn

Add block scoping

---

core/errors.py
core/interpreter.py
core/lexer.py
core/nodes.py
core/parser.py
core/tokens.py
examples/try_catch.rn

Finally, Radon is going to have a `try catch` exception handling system. Examples are in respective folders.

Try catch syntax

---

core/datatypes.py
core/interpreter.py
core/nodes.py
core/parser.py
core/tokens.py
examples/loops.rn

Existing `for..to..step` loops examples:
```radon
for i = 0 to 10 {
print(i)
}
for i = 0 to 10 step 2 {
print(i)
}
```
New `for...in` loop examples:
```radon
for i in "my string" {
print(i)
}
for i in [1, 2, 3, 4, 5] {
print(i)
}
for i in [1, 2, 3, 4, 5] {
if i == 3 {
break
}
print(i)
}
```

Added new for...in loop syntax.

---

core/datatypes.py
core/interpreter.py
core/nodes.py
core/parser.py
examples/slicing.rn

Now, Arrays and Strings elements can be change. 
Examples:
```radon
my_arr = [1,2,3,4,5,6,7,8,9,0]
my_arr[0] = 10
print(my_arr) # [10,2,3,4,5,6,7,8,9,0]
my_str = "This is an example string"
new_str = my_str[19] = "S"
print(new_str) # "This is an example String"
```

Added index setter syntax.

---

core/datatypes.py
core/interpreter.py
core/lexer.py
core/nodes.py
core/parser.py

Added `HashMap` which is `dict` in Python language.

feat: added HashMap syntax.

---

.gitignore
core/builtin_classes.py
hello.txt
tests/files.rn
tests/files.rn.json

Before, it was just a PoC for built-in classes
Closes #61

improve: `File` class

---

core/interpreter.py
stdlib/Universe.rn
tests/universe.rn
tests/universe.rn.json

Fix `Universe` module

---

core/builtin_classes.py
tests/files.rn.json

https://github.com/radon-project/radon/discussions/64#discussioncomment-9133902

[internal] add: `@check` decorator

---

core/datatypes.py

fix: Boolean returns True and False instead of true and false.

---

core/builtin_funcs.py

This removes `str_slice`, `arr_slice` as new syntax #41 has been added.
Not valid #22

fix: removed legecy str_slice and arr_slice method.

---

core/datatypes.py
core/interpreter.py
core/nodes.py
core/parser.py
core/tokens.py
tests/switch-case.rn
tests/switch-case.rn.json

Add `switch` statement

---

core/builtin_funcs.py
core/datatypes.py
core/interpreter.py
core/nodes.py
core/parser.py
radon.py
tests/closures.rn
tests/closures.rn.json
tests/scope-bug.rn
tests/scope-bug.rn.json

Add Closures

---

core/colortools.py
core/errors.py
core/interpreter.py
radon.py

I just updated base error texts with a coloring module, which is newly added as experiment.

Experimental errors color support.

---

core/builtin_classes/base_classes.py
core/builtin_classes/file_object.py
core/builtin_classes/json_object.py
core/builtin_classes/requests_object.py
core/builtin_classes/string_object.py
core/builtin_funcs.py
core/datatypes.py
core/errors.py
core/interpreter.py

Add type annotations to `core/builtin_funcs.py` and `core/builtin_classes/base_classes.py`

---

core/interpreter.py
core/nodes.py
core/parser.py
tests/modules2.rn

Implement `as` keyword for `import` statements

---

core/builtin_funcs.py
radon.py

Improved start text in shell
Added functions:
- `license()`
- `credits()`

Shell improvements
